version: "3.9"

services:
  backend:
    container_name: "backend_app"
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8067:80"
    restart: always


  chrome-node:
    image: selenium/standalone-chrome:latest
    privileged: true
    shm_size: 2g
    environment:
      - SE_NODE_SESSION_TIMEOUT=30
      - SE_NODE_MAX_SESSIONS=8
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    hostname: chrome
    restart: always
    ports:
      - "4444:4444"
      - "7900:7900"
